<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-NLF7L4D" failures="1" tests="6" name="Test" time="0.474" errors="0" timestamp="2024-01-08T23:54:16 IST">
  <testcase classname="testNG.Day1" name="first" time="0.104"/>
  <testcase classname="testNG.Day2" name="second1" time="0.141">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNG.Day2.second1(Day2.java:21)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- second1 -->
  <testcase classname="testNG.Day2" name="second2" time="0.009"/>
  <testcase classname="testNG.Day4" name="homeloan1" time="0.003"/>
  <testcase classname="testNG.Day4" name="homeloan2" time="0.015"/>
  <testcase classname="testNG.Day4" name="homeloan3" time="0.008"/>
</testsuite> <!-- Test -->
